<?php

/**
 * @file
 * Contains opencalais.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\opencalais\CalaisService;

/**
 * Implements hook_menu().
 */
function opencalais_menu() {
  $items['admin/config/content/opencalais'] = array(
    'title' => 'Open Calais Settings',
    'description' => "Configure Open Calais module.",
    'route_name' => 'opencalais.settings',
  );

  return $items;
}

/**
 * Implements hook_schema
 * @return mixed
 */

function opencalais_schema() {
  $schema['opencalais'] = [
    // Example (partial) specification for table "node".
    'description' => 'Table to store OpenCalais Tags.',
    'fields' => [
      'nid' => [
        'description' => 'The primary identifier for a node.',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'nid' => [
        'description' => 'The primary identifier for a node.',
        'type' => 'boolean',
        'default' => FALSE,
        'not null' => TRUE,
      ],
      'tags' => [
        'description' => 'The tags of this node.',
        'type' => 'longtext',
        'not null' => FALSE,
        'default' => '',
      ],
    ],
    'unique keys' => [
      'nid' => ['nid'],
    ],
    'primary key' => ['nid'],
  ];
  return $schema;
}

/**
 * Implements hook_help().
 */
function opencalais_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opencalais module.
    case 'help.page.opencalais':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Utilize the Open Calais API to tag content.') . '</p>';
      return $output;

    default:
  }
}

/*
 * Implements hook_node_update(Drupal Core Entity EntityInterface $node)
 */

function opencalais_node_update($node){
//kint($node);
  $config = $this->config('opencalais.settings');

  $options = array(
      'apiKey' => $config->get('calaisKey'),
      'contentType' => 'text/plain',
      'content' => strip_tags($body),
      'host' => $config->get('calaisHost'),
    );
  
  //$calais = opencalais_get_service($options);
  $calais = new CalaisService($options);
  //Get your tags
  $tags = $calais->analyze();
 
  kint($tags);
  //@TODO: Store the values

}

/**
 * Return the OpenCalais Service class.
 *
 * @param $options An array of option parameters to be sent to the CalaisService class.
 * @return $object The initialized CalaisService object.
 */
function opencalais_get_service($options = array()) {
  return new CalaisService($options);
}

function opencalais_form_alter(&$form, $form_state, $form_id){
  kint($form);
  drupal_set_message($form_id);
}
